name: "Pull Request Labeler"
on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, deleted]
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
