name: Label PR with LGTM on approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  label_on_approve:
    runs-on: ubuntu-latest

    steps:
      - name: Check if review is approved
        id: review_check
        run: |
          if [[ "${{ github.event.review.state }}" == "approved" ]]; then
            echo "::set-output name=review_approved::true"
          else
            echo "::set-output name=review_approved::false"
            echo "This review is not an approval. Exiting."
            exit 0
          fi

      - name: Add LGTM label
        if: steps.review_check.outputs.review_approved == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;

            await github.issues.addLabels({
              owner,
              repo,
              issue_number: pr_number,
              labels: ['lgtm']
            });
