name: Lint

on: [push]

env:
  POETRY_VERSION: "1.7.1"
  POETRY_URL: https://install.python-poetry.org

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Set Poetry environment
        run: |
          poetry env use ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          poetry install --only dev --all-extras
      - name: Lint Python (Black)
        run: |
          poetry run inv formatter
      - name: Lint Python (Ruff)
        run: |
          poetry run inv lint
      - name: Lint Python (isort)
        run: |
          poetry run inv isort
