name: Unittest

on: [push, pull_request]

env:
  POETRY_VERSION: "1.7.1"
  POETRY_URL: https://install.python-poetry.org

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pipx install poetry==1.8
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Set Poetry environment and clear cache
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry cache clear --all pypi
      - name: Install dependencies
        run: |
          poetry install --no-root --only dev --all-extras
      - name: Lint Python (Black)
        run: |
          poetry run inv formatter
      - name: Lint Python (Ruff)
        run: |
          poetry run inv lint
      - name: Lint Python (isort)
        run: |
          poetry run inv isort
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        pydantic-version: ["^1.10", "^2.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pipx install poetry==1.8
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Set Poetry environment and clear cache
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry cache clear --all pypi
      - name: Override Pydantic version
        run: |
          if [[ "${{ matrix.pydantic-version }}" == ^1.* ]]; then
            # Since there's a mismatch between pydantic 1.x and the python-semantic-release version
            # we have in the project, we need to downgrade its version when running tests on pydantic v1
            poetry remove python-semantic-release
            poetry add python-semantic-release@8.0.0
          fi
          poetry add pydantic@${{ matrix.pydantic-version }}
          poetry lock --no-update
      - name: Install dependencies
        run: |
          poetry install --all-extras
      - name: Run Tests
        env:
          AI21_API_KEY: ${{ secrets.AI21_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          poetry run pytest tests/unittests/
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
